core/urls.py
from django.urls import path

from core import views

urlpatterns = [
    path('', views.home, name='index'),
    path('contato', views.contato, name='contato'),
    
]

portifolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from core import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contatos/models.py
from django.db import models

class Contato(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    email = models.EmailField()
    motiv = models.CharField(max_length=200, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    message = models.TextField()

    def __str__(self):
        return self.name

core/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    name = models.CharField(max_length=100, blank=False, default='None')

    def __str__(self):
        return self.name

  
class Projeto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=False, null=False)
    tecnology = models.CharField(max_length=100)
    descrition = models.TextField()
    image = models.ImageField(upload_to='projetos/%y/%m/%d', blank=True)
    concluido = models.BooleanField(default=True, auto_created=True)

    def __str__(self):
        return self.name

contatos/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contato

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['name','email','motiv','message']

contatos/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render,redirect
from .models import Projeto
from contatos.forms import ContatoForm

# Create your views here.
def home(request):
    contexto = {}
    projetos = Projeto.objects.filter(concluido=True)
    


    contexto['projetos'] = projetos
    if request.method != 'POST':
        form = ContatoForm(request.POST)
        contexto['form'] = form
        return render(request, 'base.html',contexto)



    return render(request, 'base.html', contexto)

def contato(request):
    contexto = {}
    form = ContatoForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('index')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

{% include 'parciais/_head.html' %}

<body>
    <div id="video">
        <div class="preloader">
            <div class="preloader-bounce">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        {% include 'parciais/_header.html' %}
        
        {% include 'parciais/_sobre.html' %}
            
        {% include 'parciais/_servicos.html' %}
        
        {% include 'parciais/_portifolio.html' %}
        
        {% include 'parciais/_contatos.html' %}

        {% include 'parciais/_scripts.html' %}
</body>

</html>

templates/parciais/_contatos.html
{% load static %}

<div class="section animated-row" data-section="contato">
    <div class="section-inner">
        <div class="row justify-content-center">
            <div class="col-9 col-md-7 wide-col-laptop">
                <div class="title-block animate" data-animate="fadeInUp">
                    <span>Contato</span>
                    <h2>Entrar em contato</h2>
                </div>
                <div class="contact-section">
                    <div class="row">
                        <div class="col-md-5  animate" data-animate="fadeInUp">
                            <div class="contact-box">
                                <div class="contact-row">
                                    <i class="fa fa-envelope"></i> rafaelgomesalmeida@hotmail.com
                                </div>
                                <div class="contact-row">
                                    <i class="fa fa-phone"></i> 86 99821-5671
                                </div>
                                <div class="contact-row">
                                    <i class="fa fa-map-marker"></i> Trabalho Remoto
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6  animate" data-animate="fadeInUp">
                            <form  method="POST" action="{% url 'contato' %}">
                                {% csrf_token %}
                                <div class="input-field">
                                    <input class="form-control" type="text" name="name" maxlength="200" required id="id_name" required placeholder="Nome">
                                </div>
                                <div class="input-field">
                                    <input class="form-control" type="email" name="email" maxlength="254" required id="id_email" required placeholder="Email">
                                    
                                </div>
                                <div class="input-field">
                                    <input class="form-control" type="text" name="motiv" maxlength="200" id="id_motiv" required placeholder="Motivo">
                                </div>
                                <div class="input-field">
                                    <textarea class="form-control" name="message" cols="40" rows="10" required id="id_message" required placeholder="Menssagem"></textarea>
                                </div>
                                <button class="btn" type="submit">Enviar</button>
                            </form>
                            <div id="form-messages" class="mt-3 mb-1"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<div id="social-icons">
<div class="text-right">
    <ul class="social-icons">
        <li><a href="https://www.instagram.com/gomes_raff/" title="Instagram"><i
                    class="fa fa-instagram"></i></a></li>
        <li><a href="https://www.linkedin.com/in/rafaelgomesdealmeida/" title="Linkedin"><i
                    class="fa fa-linkedin"></i></a></li>
        <li><a href="https://github.com/Juzeka" title="GitHub"><i class="fa fa-github"></i></a></li>
    </ul>
</div>
</div>
</div>

templates/parciais/_head.html
{% load static %}

<head>
    <link rel = "icon" type = "imagem/png" href = "{% static 'images/favicon.png' %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="https://templatemo.com/tm-528-elegance">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,700,900" rel="stylesheet">

    <title>Portifólio Pessoal</title>
    <!--
Elegance Template
https://templatemo.com/tm-528-elegance
-->
    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/fullpage.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">

    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>

templates/parciais/_header.html
{% load static %}


<header id="header">
    <div class="container-fluid">
        <div class="navbar">
            <a href="" id="logo" title="Rafae Gomes de Almeida">
                <img src="{% static 'images/logo.png' %}" alt="">
            </a>
            <div class="navigation-row">
                <nav id="navigation">
                    <button type="button" class="navbar-toggle"> <i class="fa fa-bars"></i> </button>
                    <div class="nav-box navbar-collapse">
                        <ul class="navigation-menu nav navbar-nav navbars" id="nav">
                            <li data-menuanchor="inicio" class="active"><a href="#inicio">Inicio</a></li>
                            <li data-menuanchor="sobre"><a href="#sobre">Sobre</a></li>
                            <li data-menuanchor="servicos"><a href="#servicos">Serviços</a></li>
                            <li data-menuanchor="portifolio"><a href="#portifolio">Portifólio</a></li>

                            <li data-menuanchor="contato"><a href="#contato">Contato</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>


<video autoplay muted loop id="myVideo">
    <source src="{% static 'images/fundo.mp4' %}" type="video/mp4">
</video>

<div id="fullpage" class="fullpage-default">

    <div class="section animated-row" data-section="inicio">
        <div class="section-inner">
            <div class="welcome-box">
                <h1 id="titulo" class="welcome-title animate" data-animate="fadeInUp">Portifólio Pessoal</h1>
                <span class="welcome-first animate" data-animate="fadeInUp">Rafael Gomes de Almeida</span>
                <div class="scroll-down next-section animate data-animate=" ><img
                        src="{% static 'images/mouse-scroll.png' %}" alt=""><span>Scroll Down</span></div>
            </div>
        </div>
    </div>

templates/parciais/_portifolio.html
{% load static %}
<div class="section animated-row" data-section="portifolio">
    <div class="section-inner">
        <div class="row justify-content-center">
            <div class="col-md-8 wide-col-laptop">
                <div class="title-block animate" data-animate="fadeInUp">
                    <span>Portifólio</span>
                    <h2>Projetos desenvolvidos</h2>
                </div>
                <div class="gallery-section">
                    <div class="gallery-list owl-carousel">
                        {% for projeto in projetos %}
                            <div class="item animate" data-animate="fadeInUp">
                                <div class="portfolio-item">
                                    <div class="thumb">
                                        <img src="{{projeto.image.url}}" width="400" height="370" alt="">
                                    </div>
                                    <div class="thumb-inner animate" data-animate="fadeInUp">
                                        <h4>{{projeto.name}}</h4>
                                        <p>Categoria: {{projeto.categoria}}</p>
                                        <p>Tecnologias: {{projeto.tecnology}}</p>
                                        <p>Descrição: {{projeto.descrition}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/parciais/_scripts.html
{% load static %}

<script src="{% static 'js/jquery.js' %}"></script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/fullpage.min.js' %}"></script>

    <script src="{% static 'js/scrolloverflow.js' %}"></script>

    <script src="{% static 'js/owl.carousel.min.js' %}"></script>

    <script src="{% static 'js/jquery.inview.min.js' %}"></script>

    <script src="{% static 'js/form.js' %}"></script>

    <script src="{% static 'js/custom.js' %}"></script>

templates/parciais/_servicos.html
{% load static %}
<div class="section animated-row" data-section="servicos">
    <div class="section-inner">
        <div class="row justify-content-center">
            <div class="col-md-8 wide-col-laptop">
                <div class="title-block animate" data-animate="fadeInUp">
                    <span>Serviços</span>
                    <h2>O que faço?</h2>
                </div>
                <div class="services-section">
                    <div class="services-list owl-carousel">
                        <div class="item animate" data-animate="fadeInUp">
                            <div class="service-box">
                                <span class="service-icon"><i class="fa fa-desktop"
                                        aria-hidden="true"></i></span>
                                <h3>Websites - One Page</h3>
                                <p>Sites One Page ultiliza a mesma página para mostrar todo o seu conteúdo de uma empresa ou orgão, trata-se da aplicação do layout em uma única página web. </p>
                            </div>
                        </div>
                        <div class="item animate" data-animate="fadeInUp">
                            <div class="service-box">
                                <span class="service-icon"><i class="fa fa-laptop"
                                        aria-hidden="true"></i></span>
                                <h3>Websites - Dynamic</h3>
                                <p>O site dinâmico permite que sejam feitas alterações em seus conteúdos ao longo do tempo. As mudanças são feitas nos textos, 
                                    abas e links, de forma simples e sem que haja alterações no código fonte, 
                                    ou seja, a programação utilizada para o site funcionar</p>
                            </div>
                        </div>
                        <div class="item animate" data-animate="fadeInUp">
                            <div class="service-box">
                                <span class="service-icon"><i class="fa fa-cloud"
                                        aria-hidden="true"></i></span>
                                <h3>Sistemas Web</h3>
                                <p>Os sistemas web são desenvolvidos para tornar processos manuais mais simples, rápidos e eficazes.</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/parciais/_sobre.html
{% load static %}
<div class="section animated-row" data-section="sobre">
    <div class="section-inner">
        <div class="about-section">
            <div class="row justify-content-center">
                <div class="col-lg-8 wide-col-laptop">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="about-contentbox">
                                <div class="animate" data-animate="fadeInUp">
                                    <span>Sobre</span>
                                    <h2>Quem sou eu?</h2>
                                    <p>Chamo-me Rafael Gomes de Almeida, Bacharel em Tecnologia da Informação, 
                                        atualmente cusando o 8ª periodo. 
                                        Apaixonado por tecnologia e amante da programação, 
                                        ultilizo a linguagem <strong> Python</strong> com os <strong>Frameworks Django </strong> e <strong>Django Rest</strong> 
                                        no back-end no desenvolvimento dos meus projetos e trabalhos. </p>
                                </div>
                                <!-- classificados
                                <div class="facts-list owl-carousel">
                                    <div class="item animate" data-animate="fadeInUp">
                                        <div class="counter-box">
                                            <i class="fa fa-certificate counter-icon"
                                                aria-hidden="true"></i><span class="count-number">6</span>
                                            Certificados/Cursos
                                        </div>
                                    </div>
                                    <div class="item animate" data-animate="fadeInUp">
                                        <div class="counter-box">
                                            <i class="fa fa-file-code-o counter-icon"
                                                aria-hidden="true"></i><span class="count-number">4</span>
                                            Trabalhos/Projetos
                                        </div>
                                    </div>

                                    <div class="item animate" data-animate="fadeInUp">
                                        <div class="counter-box">
                                            <i class="fa fa-desktop counter-icon"
                                                aria-hidden="true"></i><span class="count-number">1.5</span>
                                            Anos de Experiência
                                        </div>
                                    </div>
                                    
                                </div> 
                                -->
                            </div>
                        </div>
                        <div class="col-md-5 offset-md-1 ">
                            <figure class="about-img animate" data-animate="fadeInUp"><img
                                    src="{% static 'images/eu.JPG' %}" class="rounded" width="400" alt="">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>